### PR TITLE
Implemented utp transport

### PR DESCRIPTION
**Pull request by masylum**
#### :tophat: What? Why?

First attempt to get the µtp transport implemented.

This relies on: https://github.com/mafintosh/utp/pull/7

### CODE REVIEW

**Comment by daviddias** [comment]
sweet! :D Thank you @masylum !!

**Comment by daviddias** [comment]
Oh, seems I clicked too soon

```
TAP version 13
# a test
ok 1 null
ok 2 started listening
ok 3 received incoming connection
/Users/david/Documents/code/ipfs/libp2p/node/swarm/js-libp2p-utp/node_modules/abstract-transport/tests/base-test.js:14
        listener.close(function () {
                 ^

```

Nevertheless, nice start :)  are you looking into implementing the rest?

**Comment by masylum** [comment]
I would really like if `abstract-connection` and `abstract-transport` were complete to understand what's expected. To have this one passing the current test-suite https://github.com/mafintosh/utp/pull/7 needs to be merged.

**Comment by masylum** [comment]
just heads up that mafintosh closed the PR. Will update the dependency and tests will :sparkles: magically pass

**Comment by daviddias** [comment]
> I would really like if abstract-connection and abstract-transport were complete to understand what's expected.

Right now, the first is pretty much a 'duplex-stream' and the second is what the 'net' module offers. We will get a better understanding of the boxes we need to tick for a full interface once we start looking at the go interop. Goal is to find the lowest **solid** common denominator between both languages when it comes to channels/streams and sockets, so that we can impose that for the abstractions.

**Pull request merged**
