### PR TITLE
Make libp2p-utp an happy transport and part of the libp2p blessed family

### PR DESCRIPTION
**Pull request by daviddias**
Making some progress on getting libp2p to behave as libp2p needs it to.

### CODE REVIEW

**Comment by dirkmc** [comment]
@daviddias I just want to make sure you're aware that interface-transport has recently been updated to use async/await and interface-connection is [currently being modified](https://github.com/libp2p/interface-connection/pull/29). The corresponding WIP js-libp2p-tcp PR is here: https://github.com/libp2p/js-libp2p-tcp/pull/102

**Comment by daviddias** [comment]
Thanks for letting me know, @dirkmc :)

**Comment by alanshaw** [comment]
There's a few TODOs in the code i.e. IPv6 and 0.0.0.0 support. Are they blocking this from being merged?

**Comment by daviddias** [comment]
@alanshaw it is an improvement on what was there and it doesn't break anything from what existed (in fact, just makes it work). I would be fine merging this now and then finishing the rest of the TODO separately.

**Review by alanshaw — APPROVED** [review]
LGTM

**Pull request merged**
